language: node_js
node_js:
- '0.11'
before_install:
- npm install browserify -g
install:
- npm install
before_script:
- npm link .
script:
- npm run build
- npm run test
- npm run cover
- npm run report
env:
  global:
  - secure: SJyrlaQHlo5j3rQ9/TeebXF+HkSk5D3Ka5Vr+/a8EysFdSJcVNj8Kka8xH1kF3DokPyq0Udydk9+5Atlm0+Gp2X01pToNvxJpkUyQkz6RHP6OWmuTW1IBuEPQJvbs0Vx3BmH70Lnsk7eDTh5AkxaJqRir9Z/ihJbEKkwwn+LVmhY8YD3gdp3F/jEfAy2dUhd7j831rhT6BEkL81MnUcf4pYGC0x7AQLl4L0fuS614DrQvnvmeff661yUSP55LV4Cpdb6oyFIDp7wEegjtuDP9BoiIJWywnlSbgFlhxlRMZCGIDQUR0i5bECP+SV0VrOngLZAKdiYdM4VfXYgUlCvyM2jcnjJJ/UyQUIwb6TO/U27PW9QwxM3xcOnH6WcC27jz1lT7toY79jWr1TRiTL6NWkldW5dOOJSaRMiAHnN1LEQ6iCfarFyyKJrFOFxl78miJ/8csHUuliDXAzGha5HEbJVaorO3qKp5aTeNYA5/NHqRMTdoOZ/v196xscahevIB5qmsu9F/zgfPxz7DWqcKLJ3le4Am+SEyC/p5CU7XotcPK4g5zy+jr2gsELqfK2pDDtSGi20SC7aC+3r8ALwRGzYwbhGH8YEMDV28cXTeOIWRfK2MdnvV7dQUGIWmKurzHclo4ASbGQVotY4NYIlx68RgJFDkXOeHnU4vDUFVlY=
  - secure: aHzKcBZbRiN2Nbj5PzYFL52u/VkNamHzoyZ96Gae780imU80033eB37rXFiuLYqPmm60vvgV5AN1Puq3ZPg1JEjJhw9WU+PfnkJfXfSyEtyCvY90nSgESEknTu7xz8DtFbCt15Ep2+op1t0xO8Zs46w3QyrCDrcVYiNFYgfDf6tgnht5giU4RjjjeFYA2LWRmOT3uoZZVlXwNVeOgD/KUpC8ygQZQDVGvjwm8/L5/PoeCOnOUzxdQIGfdPNMy4YO2XL0jVs9nzImf65r4CHESHr8NPpfDvwtsHWyM3o7ntSwUz7mqlr/RgdnzI3Bl7sRltGRCktx3+/LWzhxXLBnvzVrXieofIKyF0vqNhP6P3ZXg6fnzvEa0eTyHtkJHK4BeYQ4lgvxLda6HDSICtLIdsMs9YAE/fT5wQzjNnKJ0dQl1NLm9cBUjZr0NrIYOTS/utel/mlBmYztDdomDitpE4XaQP0WoyKMPn6tXKgC2P9vUvuuVESIPWPHNjSI4gi5rb4kBB/A1q0sGuOhAH20jwP/8zulwNzFMEsh4PoeNK722kgr8QmWTqX89cnBz6VwUevz9G3BBQGv2N6xyW2Zfhz958TMikNjBqTCp+Ms5WQ6tE4vNzKwxNZ8qLIRKaR8jPhFlc/Hk37uNYxY2zg/+5ODhpPJtSSSQxDAIaCBhjU=
